// V2.0 登舰考试 · 10 套调研题库种子数据
// 来源：《需要，请继续生成剩下的6套_20260912.docx》调研问卷
// 转换为 exam_official_question 表的插入数据

export interface SeedQuestion {
  title: string;
  questionType: "essay" | "single" | "multiple";
  options?: Record<string, string>;
  judgeRule?: string;
  eightDimTags: string;
  career21Tags: string;
  industry: string;
  weightScore: number;
  status: number;
}

export const SEED_EXAM_QUESTIONS: SeedQuestion[] = [
  // ==================== 医疗健康行业 ====================
  {
    title: "在DRG/DIP支付改革背景下，你负责的业务线如何平衡医疗质量与经济效益？请结合实际案例说明。",
    questionType: "essay",
    eightDimTags: "systematic,executing,empathy",
    career21Tags: "meteor_tactician,fleet_commander,star_dock_keeper",
    industry: "医疗健康",
    weightScore: 8,
    status: 1,
  },
  {
    title: "如果一名核心医生因高压出现心理问题，且引发患者投诉，你作为管理者如何处理？",
    questionType: "essay",
    eightDimTags: "empathy,communication,executing",
    career21Tags: "star_bridge_engineer,fleet_commander,voyage_archivist",
    industry: "医疗健康",
    weightScore: 7,
    status: 1,
  },
  {
    title: "讲一个你通过优化流程，切实降低医疗风险或提升运营效率的真实案例。",
    questionType: "essay",
    eightDimTags: "systematic,executing,curiosity",
    career21Tags: "trajectory_pilot,wind_balance_officer,engine_chief",
    industry: "医疗健康",
    weightScore: 7,
    status: 1,
  },
  {
    title: "你对'互联网+医疗'或'AI辅助诊断'怎么看？请讲出技术落地的难点、伦理风险和试点数据。",
    questionType: "essay",
    eightDimTags: "curiosity,imagination,abstract",
    career21Tags: "star_chart_scholar,future_oracle,quantum_hypothesist",
    industry: "医疗健康",
    weightScore: 6,
    status: 1,
  },
  {
    title: "当科室主任为了创收要求过度医疗，你怎么管？请给出基于制度、数据和沟通的解决方案。",
    questionType: "essay",
    eightDimTags: "communication,systematic,empathy",
    career21Tags: "star_dock_keeper,star_covenant_observer,meteor_tactician",
    industry: "医疗健康",
    weightScore: 8,
    status: 1,
  },

  // ==================== 教育/培训行业 ====================
  {
    title: "你设计的这门课，完课率和好评率是多少？你怎么证明学生真的学会了？",
    questionType: "essay",
    eightDimTags: "systematic,executing,abstract",
    career21Tags: "wind_balance_officer,trajectory_pilot,voyage_archivist",
    industry: "教育培训",
    weightScore: 8,
    status: 1,
  },
  {
    title: "如果政策突然收紧（如双减），你负责的业务线如何转型？",
    questionType: "essay",
    eightDimTags: "ambiguity,imagination,executing",
    career21Tags: "future_oracle,meteor_tactician,mechanical_designer",
    industry: "教育培训",
    weightScore: 7,
    status: 1,
  },
  {
    title: "讲一个你通过优化教学服务，显著提升续费率或转介绍率的案例。",
    questionType: "essay",
    eightDimTags: "executing,communication,curiosity",
    career21Tags: "meteor_sharpshooter,shuttle_herald,trajectory_pilot",
    industry: "教育培训",
    weightScore: 7,
    status: 1,
  },
  {
    title: "你对AI在教育中的应用怎么看？请讲出具体场景（如自适应学习、作业批改）、局限性和试点效果。",
    questionType: "essay",
    eightDimTags: "curiosity,imagination,abstract",
    career21Tags: "star_chart_scholar,starlight_poet,quantum_hypothesist",
    industry: "教育培训",
    weightScore: 6,
    status: 1,
  },
  {
    title: "请描述一个你从0到1搭建的课程体系或师资培养体系。你如何定义'好课'？过程中如何解决跨科室协作难题？",
    questionType: "essay",
    eightDimTags: "systematic,abstract,communication",
    career21Tags: "engine_chief,mechanical_designer,star_covenant_observer",
    industry: "教育培训",
    weightScore: 8,
    status: 1,
  },

  // ==================== 政府/事业单位/国企 ====================
  {
    title: "在政策模糊地带，你如何既推进工作，又确保合规不出错？",
    questionType: "essay",
    eightDimTags: "ambiguity,systematic,empathy",
    career21Tags: "meteor_tactician,star_dock_keeper,fleet_commander",
    industry: "政府国企",
    weightScore: 8,
    status: 1,
  },
  {
    title: "如果群众因误解政策而情绪激动，你作为现场负责人如何处理？",
    questionType: "essay",
    eightDimTags: "empathy,communication,executing",
    career21Tags: "star_bridge_engineer,shuttle_herald,fleet_commander",
    industry: "政府国企",
    weightScore: 7,
    status: 1,
  },
  {
    title: "讲一个你通过优化流程，切实提升办事效率或群众满意度的案例。",
    questionType: "essay",
    eightDimTags: "systematic,executing,curiosity",
    career21Tags: "trajectory_pilot,wind_balance_officer,mechanical_designer",
    industry: "政府国企",
    weightScore: 7,
    status: 1,
  },
  {
    title: "你对'放管服'改革怎么看？请讲出具体痛点、改革难点和试点经验。",
    questionType: "essay",
    eightDimTags: "curiosity,abstract,ambiguity",
    career21Tags: "star_chart_scholar,wanderer_philosopher,quantum_hypothesist",
    industry: "政府国企",
    weightScore: 6,
    status: 1,
  },
  {
    title: "当上级要求和群众诉求冲突时，你怎么处理？请给出基于政策、情感和沟通的解决方案。",
    questionType: "essay",
    eightDimTags: "communication,empathy,systematic",
    career21Tags: "star_covenant_observer,star_bridge_engineer,meteor_tactician",
    industry: "政府国企",
    weightScore: 8,
    status: 1,
  },

  // ==================== 创意/广告/传媒行业 ====================
  {
    title: "你那个刷屏案例，核心洞察是什么？怎么验证的？客户为什么买单？",
    questionType: "essay",
    eightDimTags: "curiosity,abstract,communication",
    career21Tags: "interstellar_scout,quantum_hypothesist,starlight_poet",
    industry: "创意广告",
    weightScore: 8,
    status: 1,
  },
  {
    title: "如果预算砍半，但KPI不变，你这个创意怎么改？",
    questionType: "essay",
    eightDimTags: "imagination,systematic,executing",
    career21Tags: "starlight_poet,mechanical_designer,meteor_sharpshooter",
    industry: "创意广告",
    weightScore: 7,
    status: 1,
  },
  {
    title: "讲一个你通过创意，切实解决客户商业问题（如销量、知名度）的案例。",
    questionType: "essay",
    eightDimTags: "imagination,executing,communication",
    career21Tags: "starlight_poet,meteor_sharpshooter,shuttle_herald",
    industry: "创意广告",
    weightScore: 7,
    status: 1,
  },
  {
    title: "你最近关注到什么新的文化现象或消费趋势？请讲出具体案例、底层逻辑和创意启发。",
    questionType: "essay",
    eightDimTags: "curiosity,imagination,abstract",
    career21Tags: "future_oracle,interstellar_scout,starlight_poet",
    industry: "创意广告",
    weightScore: 6,
    status: 1,
  },
  {
    title: "当客户要求和品牌调性严重冲突时，你怎么处理？请给出基于专业、数据和沟通的解决方案。",
    questionType: "essay",
    eightDimTags: "communication,systematic,empathy",
    career21Tags: "star_bridge_engineer,star_covenant_observer,fleet_commander",
    industry: "创意广告",
    weightScore: 8,
    status: 1,
  },

  // ==================== 通用八维能力评测题 ====================
  {
    title: "你最近研究过哪些新的技术、工具或管理方法？有没有做过小范围试点？请详述。",
    questionType: "essay",
    eightDimTags: "curiosity",
    career21Tags: "star_chart_scholar,interstellar_scout,future_oracle",
    industry: "通用",
    weightScore: 6,
    status: 1,
  },
  {
    title: "如果明天行业政策突变，你负责的业务线有什么备选方案？",
    questionType: "essay",
    eightDimTags: "imagination,ambiguity",
    career21Tags: "future_oracle,starlight_poet,meteor_tactician",
    industry: "通用",
    weightScore: 6,
    status: 1,
  },
  {
    title: "请用非专业语言向一个外行人解释，为什么你当前的方案是最优的。",
    questionType: "essay",
    eightDimTags: "abstract,communication",
    career21Tags: "star_bridge_engineer,starlight_poet,quantum_hypothesist",
    industry: "通用",
    weightScore: 6,
    status: 1,
  },
  {
    title: "把'提升用户满意度'这个目标，拆解为具体环节的改进动作。",
    questionType: "essay",
    eightDimTags: "systematic",
    career21Tags: "trajectory_pilot,mechanical_designer,wind_balance_officer",
    industry: "通用",
    weightScore: 7,
    status: 1,
  },
  {
    title: "讲一个你如何在时间紧、任务重、资源少的情况下，保质保量完成任务的经历。",
    questionType: "essay",
    eightDimTags: "executing",
    career21Tags: "star_blacksmith,circuit_runner,meteor_sharpshooter",
    industry: "通用",
    weightScore: 7,
    status: 1,
  },
  {
    title: "当跨部门协作中出现推诿扯皮时，你如何推动问题解决？",
    questionType: "essay",
    eightDimTags: "communication",
    career21Tags: "star_bridge_engineer,fleet_commander,shuttle_herald",
    industry: "通用",
    weightScore: 7,
    status: 1,
  },
  {
    title: "在信息不全、时间紧迫的突发事件中，你如何做出决策并承担责任？",
    questionType: "essay",
    eightDimTags: "ambiguity",
    career21Tags: "meteor_tactician,fleet_commander,star_dock_keeper",
    industry: "通用",
    weightScore: 8,
    status: 1,
  },
  {
    title: "有没有一次，你因为坚持原则或纪律，而顶住了来自上级或利益相关方的压力？请详述过程。",
    questionType: "essay",
    eightDimTags: "empathy",
    career21Tags: "star_dock_keeper,star_bridge_engineer,star_covenant_observer",
    industry: "通用",
    weightScore: 8,
    status: 1,
  },

  // ==================== 通用选择题 ====================
  {
    title: "面对一个全新的复杂问题，你的第一反应通常是？",
    questionType: "single",
    options: { A: "立即动手尝试，边做边调整", B: "先搜集资料、分析拆解，再制定方案", C: "寻求他人意见，集思广益", D: "从类似经验中找类比，推导方案" },
    judgeRule: JSON.stringify({ correct: ["B"] }),
    eightDimTags: "curiosity,systematic,abstract",
    career21Tags: "star_chart_scholar,quantum_hypothesist,engine_chief",
    industry: "通用",
    weightScore: 5,
    status: 1,
  },
  {
    title: "团队中两个核心成员发生严重分歧，你作为管理者会？",
    questionType: "single",
    options: { A: "快速拍板，按我的判断决定", B: "分别倾听双方，组织沟通寻求共识", C: "引入第三方仲裁", D: "暂缓决策，收集更多数据" },
    judgeRule: JSON.stringify({ correct: ["B"] }),
    eightDimTags: "empathy,communication,ambiguity",
    career21Tags: "star_bridge_engineer,fleet_commander,star_covenant_observer",
    industry: "通用",
    weightScore: 6,
    status: 1,
  },
  {
    title: "以下哪些是你认为推动创新落地必备的能力？（多选）",
    questionType: "multiple",
    options: { A: "敏锐的问题发现能力", B: "系统化拆解能力", C: "快速执行闭环", D: "跨域沟通协作", E: "风险预判与底线守护" },
    judgeRule: JSON.stringify({ correct: ["A", "B", "C", "D", "E"] }),
    eightDimTags: "curiosity,systematic,executing,communication,empathy",
    career21Tags: "star_chart_scholar,trajectory_pilot,star_blacksmith,star_bridge_engineer,star_dock_keeper",
    industry: "通用",
    weightScore: 5,
    status: 1,
  },
];